### ISSUE TITLE
add The error body from get_contact_by_email api to the error in the rejected promise in "createRequest"

### ISSUE THREAD

**Issue by diogonlucena** [HubSpotWebTeam/hs-node-api#70]
I'm not sure if I'm doing something wrong but when contacts.getByEmail fails, the returned error doesn't contain the body the original api returns.

I would expect to see the following + the statusCode:
```
  "status": "error",
    "message": "contact does not exist",
    "correlationId": <some UUID>,
    "errors": [{
        "message": "The contact john-doe@gmail.com does not exist."
    }],
    "category": "OBJECT_NOT_FOUND",
    "requestId": <someID>
```

This would help me because I would know that I got the statusCode 404 and the reason being "contact does not exist" would make me call createOrUpdateContact

The actual error I got from console.log(JSON.stringfy(error, null, 2))

```
{
  "message": "Request failed with status code 404",
  "name": "Error",
  "stack": "Error: Request failed with status code 404\n    at createError (path-to-node-modules/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (path-to-node-modules/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (path-to-node-modules/node_modules/axios/lib/adapters/http.js:237:11)\n    at IncomingMessage.emit (events.js:201:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:471:20)\n    at endReadableNT (_stream_readable.js:1130:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:17)",
  "config": {
    "url": "https://api.hubapi.com/contacts/v1/contact/email/john-doe@gmail.com/profile?propertyMode=value_only&formSubmissionMode=none&hapikey=<my-key>&showListMemberships=false&property=firstname",
    "method": "get",
    "data": "{}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "User-Agent": "axios/0.19.0",
      "Content-Length": 2
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 30000,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
```

As you can see the expected message is not present anywhere.

**Comment by diogonlucena** [comment]
JSON.stringify won't print all the object properties (only yhe ones defined in toJson or enumerables properties) that's why I couldn't see the object I was looking for.
The path to what I want is error.response.data

Thanks for the lib ^^
